### ISSUE TITLE
Cache works but just partially

### ISSUE THREAD

**Issue by mleszcz** [c-hive/gha-yarn-cache#7] opened 2021-05-18 09:10 UTC
We use rails and this issue causes our `rake assets:precompile` is executed but it should be skipped.

I'd appreciate if you could help us spot the issue.

![Screenshot from 2021-05-18 11-04-48](https://user-images.githubusercontent.com/72438/118624651-a20cf600-b7c9-11eb-8fbb-2e5774e65a18.png)

**Comment by thisismydesign** [comment] 2021-05-18 09:22
Hi @mleszcz, I can't help you with rails related stuff. I also can't tell what your issue is based on this. What part works? What part doesn't work? You can try to switch back to the manual cache setup and explain the differences. For now, I'm closing this but if you provide more info and it turns out to be a reproducible issue I will reopen.

**Closed as completed by thisismydesign** 2021-05-18 09:22 UTC

**Comment by mleszcz** [comment] 2021-05-20 12:32
Resolved https://docs.cypress.io/guides/continuous-integration/github-actions#Caching-Dependencies-and-Build-Artifacts
