### ISSUE TITLE
Cache key changes every run (Cache not found)

### ISSUE THREAD

**Issue by likern** [c-hive/gha-yarn-cache#4] opened 2020-11-10 19:40 UTC
I'm using this action to cache `yarn install` command. It looks like it doesn't work as expected. I have this action to run on PR.

```yarml
name: build

on: pull_request

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - name: Setup Node.js
        uses: actions/setup-node@c6fd00ceb9747fb23ffdf72987450a2664414867
        with:
          node-version: 14.x
      - name: Cache yarn dependencies
        uses: c-hive/gha-yarn-cache@f23816cdbc6d287b7982b4a08096db01a6329c12
      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive
      - name: Build application
        ...
```

I see this output
```bash
Run c-hive/gha-yarn-cache@f23816cdbc6d287b7982b4a08096db01a6329c12
/bin/uname
Linux
/usr/bin/yarn cache dir
/home/runner/.cache/yarn/v6
Cache keys: Linux-yarn-cache-ac1bc0429a625b475ce3c9a27574f060, Linux-yarn-cache-
Cache not found
```

while on previous run cache key was different
```bash
Cache keys: Linux-yarn-cache-797ad193309ea75845ea8bcba98b7787
```

And every time I see different cache key generated / used on action.
**How to solve this?**

**Comment by likern** [comment] 2020-11-10 19:59
If I rerun existing workflow it finds cache
```bash
/bin/uname
Linux
/usr/bin/yarn cache dir
/home/runner/.cache/yarn/v6
Cache keys: Linux-yarn-cache-de1bc7542a625b348ce3c9a4457114f060, Linux-yarn-cache-
Cache Size: ~440 MB (461063346 B)
/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/3bd90b09-eb04-4140-8d61-78acd92e3d5b/cache.tzst -P -C /home/runner/work/Feeve/Feeve
Cache restored from key: Linux-yarn-cache-de1bc7542a625b348ce3c9a4457114f060
```

**Comment by martinlehoux** [comment] 2020-12-30 15:48
On my side, the caching works, but using https://github.com/Borales/actions-yarn doesn't work : yarn still takes 45s to install all dependencies

**Comment by jacob-israel-turner** [comment] 2021-03-09 17:25
I'm having a similar issue here.  Every time the workflow runs, I get this:
>Cache keys: Linux-yarn-cache-0aa1e6914bb37d08c02b6603fc4aec00, Linux-yarn-cache-
Cache not found


And the post job logs this:
>Warning:  reserveCache failed: Cache already exists. Scope: refs/heads/jt/yarn-cache, Key: Linux-yarn-cache-0aa1e6914bb37d08c02b6603fc4aec00, Version: 616a2e26edf1bdd55692ed301c7fcefd5f22d566d659d5f4bd045c21bcb1f337

Same results, even on multiple runs.  It seems the cache is failing to set in the post-job or something?  Or maybe it was set incorrectly in the first place, and now it can't recover from a bad state?

**Comment by thisismydesign** [comment] 2021-05-18 09:36
Hi everyone, there are multiple possible issues referenced here. I don't think any of them is an issue with this action. Make sure to check the readme about how this action works. I'll answer everyone below. Let me know if you're still having issues, otherwise, I will close this soon. If your problem is not related to the original issue, open a new one.

@likern That key is based on `yarn.lock`. See: https://github.com/c-hive/gha-yarn-cache/blob/f23816cdbc6d287b7982b4a08096db01a6329c12/src/restore.js#L37 When that file changes the cache is recreated. Can you confirm if that file changes? You could also try to use the [manual solution](https://github.com/actions/cache/blob/9ab95382c899bf0953a0c6c1374373fc40456ffe/examples.md#node---yarn) and cehck if it's any different. If it's the same, the issue is somewhere in your setup. It makes sense that it finds the cache when you re-run the job.

@martinlehoux We only store the Yarn cache directory as recommended. Your dependencies will still have to be installed which can take some time. You could cache node_modules to be faster but that can lead to issues. In any case, this is a different issue. You can open an Issue / PR for optional support to cache node_modules instead.

@jacob-israel-turner That's likely an issue with the cache action from github. See https://github.com/actions/cache/issues/144

**Comment by thisismydesign** [comment] 2021-09-06 17:13
No replies, closing.

**Closed as completed by thisismydesign** 2021-09-06 17:13 UTC
